### root domain test
GET http://localhost:8000/

#### ADMIN API ####
### get admin api
GET http://localhost:8000/api/v1/admin

### post admin api
POST http://localhost:8000/api/v1/admin
Content-Type: application/json

{
    "fName": "admin",
    "lName": "admin",
    "email": "4admin@admin.com",
    "phone": "1234567890",
    "address": "admin",
    "dob": "2020-01-01",
    "password": "admin"
    
}

### post admin email verification api
POST http://localhost:8000/api/v1/admin/email-verification
Content-Type: application/json

{
    "email": "admin@admin.com",
    "emailValidationCode": "85f780d2-c4e4-43bc-bb47-673f977ca22b"
    
}

### admin login api
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json

{
    "email": "h@d.com",
    "password": "123456"
    
}

### admin update password api
PATCH http://localhost:8000/api/v1/admin/update-password
Content-Type: application/json
# aaaaA11
# bbbbB11

{
    "email": "dahalhimanshu@hotmail.com",
    "password": "123456",
    "currentPassword" : "aaaaA11"
    

    
}

### patch admin api
PATCH http://localhost:8000/api/v1/admin

###=== category section =====

### Post new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "catName" : "Television"
}

### Get all active categories
GET http://localhost:8000/api/v1/category


### update status of categories
PATCH http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "_id": "62a7dbc486f4df82297133eb",
    "status" : "active"
    
}

#============= Product api
### post product
POST http://localhost:8000/api/v1/products
Content-Type:application/json

{
    "name": "MacBook Pro 14 Inch",
    "sku": "MBP-14" ,
    "description": "lorem impsum ",
    "qty": 100,
    "price": 3000,
    "salesPrice": 0,
    "salesDate": null
}


### get all product
GET http://localhost:8000/api/v1/products

### get single product
GET http://localhost:8000/api/v1/products/62b0f97a65c74d297be5a263

### update product
PUT http://localhost:8000/api/v1/products
Content-Type:application/json

{
"catId": "62afc36dc061d755283b8891",
"description": "dsdsdddsdssds",
"name": "ds",
"price": 98,
"qty": 100,
"salesEndDate": null,
"salesPrice": 0,
"salesStartDate": null,
"status": "active",
"_id": "62b90273e15222661aea449e"
}   

#====== payment method api
### get all payment methods
GET http://localhost:8000/api/v1/payment-method

### post payment methods
POST http://localhost:8000/api/v1/payment-method
Content-Type: application/json

{
    "name": "Pay by Bank Transferssss",
    "status": "inactive",
    "description": "Please EFT to the following accounts BAS: 43434, AC:808008080"
}

### update payment methods
PUT http://localhost:8000/api/v1/payment-method
Content-Type: application/json

{
    "_id": "62ba30bbdd42545240d2a7ef",
    "name": "Pay by Credit Card",
    "status": "active",
    "description": "Use this payment is to Pay by Card"
}


### delete
# DELETE  http://localhost:8000/api/v1/payment-method/
DELETE  http://localhost:8000/api/v1/payment-method/62ba3cb85fe56c69566e040a

